name: Arduino Library CI

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: install arduino libraries
      run: arduino --install-library "SSD1306Ascii","Adafruit ESP8266"

    - name: test platforms
      run: python3 ci/build_platform.py main_platforms
